### ISSUE TITLE
reference to paper in README?

### ISSUE THREAD

**Issue by peschue** [conll/reference-coreference-scorers#4]
As far as I understand this is the new repository location for the software linked in the following paper.

Pradhan, S., Luo, X., Recasens, M., Hovy, E., Ng, V., & Strube, M. (2014). Scoring Coreference Partitions of Predicted Mentions: A Reference Implementation. In Annual Meeting of the Association for Computational Linguistics (Vol. 2, pp. 30–35). http://www.aclweb.org/anthology/P/P14/P14-2006

If this is the case, to make citations easier I would suggest to add this reference to the README file that is visible on the entry page of the repository.

**Comment by sameer-pradhan** [comment]
You are correct. Thanks for the suggestion. I always fall so much behind documentation. I will do that right now. Let me know if you have any more suggestions, or just create a pull request :-)

**Comment by peschue** [comment]
Thank you. Next time I make a PR. ;)
